### ISSUE TITLE
make the llvm-ar not found failure a bit more informative

### ISSUE THREAD

**Issue by ianamason** [SRI-CSL/whole-program-llvm#7]
```
Traceback (most recent call last):
  File "/vagrant/whole-program-llvm/extract-bc", line 380, in <module>
    sys.exit(main(sys.argv))
  File "/vagrant/whole-program-llvm/extract-bc", line 327, in main
    process_file_unix(inputFile, outputFile, llvmLinker, llvmArchiver)
  File "/vagrant/whole-program-llvm/extract-bc", line 349, in process_file_unix
    return handleExecutable(inputFile, outputFile, extractor, llvmLinker)
  File "/vagrant/whole-program-llvm/extract-bc", line 153, in handleExecutable
    linkProc = Popen(linkCmd)
  File "/vagrant/whole-program-llvm/driver/popenwrapper.py", line 15, in Popen
    return subprocess.Popen(*pargs,**kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by ianamason** [comment]
09d218125492d2030
Fixed.
